url=https://tutorialsninja.com/demo/
browserName=Chrome


#Existing UserDetails
FirstName=tutorialsninja
LastName=demoqa
qaValidEmail=tutorialsninja.demoqa@yopmail.com
qaValidPassword=demoqa0465194431
ValidTelephone=0465194431